export const ErrorCodes = {
  INVALID_CREDENTIALS: 'AUTH001',
  EMAIL_ALREADY_EXISTS: 'AUTH002',
  INVALID_VERIFICATION_CODE: 'AUTH003',
  TOKEN_EXPIRED: 'AUTH004',

  COURT_NOT_FOUND: 'COURT001',
  INVALID_COURT_DATA: 'COURT002',

  RESERVATION_NOT_FOUND: 'RESV001',
  INVALID_RESERVATION_STATUS: 'RESV002',
  UNAVAILABLE_TIME_SLOT: 'RESV003',
  RESERVATION_CANCEL_REQUEST_INVALID: 'RESV004',
  INVALID_RESERVATION_TYPE: 'RESV005',
  INVALID_RESERVATION_DATES: 'RESV006',

  USER_NOT_FOUND: 'USER001',
  INVALID_USER_DATA: 'USER002',

  INTERNAL_SERVER_ERROR: 'INTERNAL001',
} as const;
