export const ErrorCodes = {
  INVALID_CREDENTIALS: 'AUTH001',
  EMAIL_ALREADY_EXISTS: 'AUTH002',
  INVALID_VERIFICATION_CODE: 'AUTH003',
  TOKEN_EXPIRED: 'AUTH004',
  DOCUMENT_ALREADY_EXISTS: 'AUTH005',
  VERIFICATION_CODE_EXPIRED: 'AUTH006',
  USER_NOT_FOUND: 'AUTH007',

  COURT_NOT_FOUND: 'COURT001',
  INVALID_COURT_DATA: 'COURT002',

  RESERVATION_NOT_FOUND: 'RESV001',
  INVALID_RESERVATION_STATUS: 'RESV002',
  UNAVAILABLE_TIME_SLOT: 'RESV003',
  RESERVATION_CANCEL_REQUEST_INVALID: 'RESV004',
  INVALID_RESERVATION_TYPE: 'RESV005',
  INVALID_RESERVATION_DATES: 'RESV006',

  INVALID_USER_DATA: 'USER002',

  INTERNAL_SERVER_ERROR: 'INTERNAL001',

  PAYMENT_FAILED: 'PAY001',
  WEBHOOK_FAILED: 'PAY002',

  NO_SUBSCRIPTION_PLAN: 'SUB001',
  SUBSCRIPTION_PLAN_NOT_FOUND: 'SUB002',
  COURT_LIMIT_EXCEEDED: 'SUB003',
  INVALID_SUBSCRIPTION_PLAN: 'SUB004',
  SUBSCRIPTION_EXPIRED: 'SUB005',
  SUBSCRIPTION_UPGRADE_FAILED: 'SUB006',
  SUBSCRIPTION_PLAN_CREATION_FAILED: 'SUB007',
  SUBSCRIPTION_CREATE_ERROR: 'SUB008',

  BILLING_NOT_FOUND: 'BILL001',
  BILLING_UPDATE_FAILED: 'BILL002',

  UNAUTHORIZED: 'UNAUTHORIZED001',

  DASHBOARD_NOT_FOUND: 'DASH001',
  DASHBOARD_GET_FAILED: 'DASH002',

  EVENT_NOT_FOUND: 'EVENT001',
  EVENT_ALREADY_EXISTS: 'EVENT002',
  EVENT_CREATION_FAILED: 'EVENT003',
  EVENT_UPDATE_FAILED: 'EVENT004',
  EVENT_DELETE_FAILED: 'EVENT005',

  NOTIFICATION_NOT_FOUND: 'NOTIF001',
  NOTIFICATION_CREATION_FAILED: 'NOTIF002',
  NOTIFICATION_UPDATE_FAILED: 'NOTIF003',
  NOTIFICATION_DELETE_FAILED: 'NOTIF004',
} as const;
