FROM node:18-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

FROM node:18-alpine

WORKDIR /app

COPY --from=builder /app .

RUN npm install

ENV NODE_ENV=production

# OpenTelemetry - Usando variáveis do .env
ENV OTEL_SERVICE_NAME=${OTEL_SERVICE_NAME}
ENV OTEL_RESOURCE_ATTRIBUTES=${OTEL_RESOURCE_ATTRIBUTES}
ENV OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
ENV OTEL_EXPORTER_OTLP_PROTOCOL=${OTEL_EXPORTER_OTLP_PROTOCOL}

# Grafana Cloud OpenTelemetry - Usando variáveis do .env
ENV GRAFANA_CLOUD_INSTANCE_ID=${GRAFANA_CLOUD_INSTANCE_ID}
ENV GRAFANA_CLOUD_API_KEY=${GRAFANA_CLOUD_API_KEY}
ENV GRAFANA_CLOUD_OTLP_ENDPOINT=${GRAFANA_CLOUD_OTLP_ENDPOINT}

EXPOSE 3000

CMD ["npm", "run", "start:prod"]
