version: '3'
services:
  app:
    container_name: sportvenue_backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - NODE_ENV=production
    networks:
      - sportvenuenetwork

networks:
  sportvenuenetwork:
    driver: bridge
