export enum CourtCategories {
  FOOTBALL = 'FOOTBALL',
  BASKETBALL = 'BASKETBALL',
  VOLLEYBALL = 'VOLLEYBALL',
  TENNIS = 'TENNIS',
  FUTSAL = 'FUTSAL',
  HANDBALL = 'HANDBALL',
  BEACH_VOLLEYBALL = 'BEACH_VOLLEYBALL',
  BEACH_TENNIS = 'BEACH_TENNIS',
  RUGBY = 'RUGBY',
  GOLF = 'GOLF',
}
